[zook]
    port       = 8080
    http_svcs  = static_svc,dynamic_svc
    extra_svcs = echo_svc,auth_svc,log_svc,xfer_svc

[zookd]
    cmd = zookd
    uid = 61011
    gid = 1000
    dir = /jail

[static_svc]
    cmd = zookfs
    url = .*\.(html|css|jpg|png|ico)
    uid = 61013
    gid = 1000
    dir = /jail
    args = 61009 1000

[dynamic_svc]
    cmd = zookfs
    url = (/|.*zoobar/index\.(cgi|py).*|/zoobar)
    uid = 61014
    gid = 1000
    dir = /jail
    args = 61015 1000

[echo_svc]
    cmd = zooksvc
    args = /echosvc/sock /zoobar/svc-echo.py
    dir = /jail
    uid = 61010
    gid = 61010

[auth_svc]
    cmd = zooksvc
    args = /authsvc/sock /zoobar/svc-auth.py
    dir = /jail
    uid = 61016
    gid = 1000

[log_svc]
    cmd = zooksvc
    args = /logsvc/sock /zoobar/svc-log.py
    dir = /jail
    uid = 61017
    gid = 1000

[xfer_svc]
    cmd = zooksvc
    args = /xfersvc/sock /zoobar/svc-xfer.py
    dir = /jail
    uid = 61018
    gid = 1000
    extra_gids = 61018
